language: android
android:
  components:
    - android-23
    - android-24


sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

before_script:
- android update sdk --filter build-tools-24.0.1 --no-ui

script: ./gradlew --stacktrace app:assembleDebug
