language: android

android:
  components:
    - tools
    - build-tools-25.0.2
    - android-23
    - android-25
    - extra-android-m2repository

jdk:
  - oraclejdk8

sudo: false

# before_cache:
#   - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
#   - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
# cache:
#   directories:
#   - $HOME/.m2
#   - $HOME/.gradle/caches/
#   - $HOME/.gradle/wrapper/

script: ./gradlew --stacktrace app:assembleDebug
