language: android

android:
  components:
    - tools
    - build-tools-24.0.1
    - android-23
    - android-24

jdk:
  - oraclejdk8

sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

script: ./gradlew --stacktrace app:assembleDebug
